### PR TITLE
drop nodes < 18

### PR DESCRIPTION
**Pull request by patricklx**
https://github.com/ember-cli/eslint-plugin-ember/issues/1535
also, took this change to switch to eslint plugin n

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Thank you!

**Comment by bmish** [comment]
Can you please drop Node 19 as well?

**Comment by patricklx** [comment]
Node 19 is excluded.
according to https://nodejs.org/en/about/previous-releases  18.x is LTS... strangly 19 isnt

**Comment by bmish** [comment]
Okay nevermind looks good. Could have simplified to `18.* || >=20` but what you have is fine.

**Pull request merged**
