### PR TITLE
Add new ember-data rule: `require-async-inverse-relationship`

### PR DESCRIPTION
**Pull request by wozny1989**
# Task:
 - Lints according to this deprecation https://deprecations.emberjs.com/id/ember-data-deprecate-non-strict-relationships
 - fixes: https://github.com/ember-cli/eslint-plugin-ember/issues/1776

### CODE REVIEW

**Comment by wozny1989** [comment]
@NullVoxPopuli What do you think about this?

**Comment by NullVoxPopuli** [comment]
Adding new recommended rules is a breaking change -- this new rule would have to be left out of the recommended set until the next major of eslint-plugin-ember.

As for the lint rule itself -- I'll let @runspired speak to that.

Code seems :+1:

**Comment by runspired** [comment]
@NullVoxPopuli unclear to me on breaking changes when its a lint to support something that was deprecated and removed a full major version ago in EmberData itself.

That said: @wozny1989 think you could PR this to EmberData instead? we have the infra for a rules package we intended to start adding rules to (including this one) here https://github.com/emberjs/data/tree/main/packages/eslint-plugin-ember-data

**Comment by bmish** [comment]
The rule can be made `recommended` later but not when it's initially added, as mentioned here: https://github.com/ember-cli/eslint-plugin-ember#creating-a-new-rule

> Note that new rules should not immediately be added to the [recommended](https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/recommended-rules.js) configuration, as we only consider such breaking changes during major version updates.

**Comment by wozny1989** [comment]
@bmish Sorry, I didn't notice thing about recommendation, just pushed changes and fix lint errors on CI

**Comment by bmish** [comment]
Are we good to go with this? I don't mind having Ember Data rules in this plugin for now as we already have a couple and this plugin is widely used.

**Pull request merged**
