### PR TITLE
No unused dependent properties

### LINKED ISSUE #2: New rule proposal - "no-unused-dependent-properties"
Proposed rule should check if there are any unused dependent properties in computed properties.

Correct:
```
test: computed('a', 'b', function() {
    return get(this, 'a') + get(this, 'b');
}),
```

Incorrect:
```
test: computed('a', 'b', function() {
    return get(this, 'a') + 'asd';
}),
```

### PR DESCRIPTION
**Pull request by alexlafroscia**
Closes #2

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Hmm, this PR probably needs to be rebased since my other PR to update the directory structure to match the Yeoman generator.

**Comment by michalsnik** [comment]
Thanks @alexlafroscia , np.

**Comment by michalsnik** [comment]
Hey @alexlafroscia, I didn't got chance to work on this unfortunately... If you'd like to proceed with this PR, you're good to go :)

**Comment by alexlafroscia** [comment]
I'm going to close this. I might re-open it from `master` since this PR is so stale.

**Pull request closed without merging**
