### PR TITLE
Allow recognition of controller injection

### PR DESCRIPTION
**Pull request by rmachielse**
This is useful to dictate the position of controller injections in `order-in-controllers`, similar to `service`.

This does not yet add the `controller` property to the default order of the `order-in-controllers` rule.
I'm not sure what the convention should be, I guess before `service` injections?

### CODE REVIEW

**Comment by rmachielse** [comment]
@rwjblue @Turbo87 I also have this proposal. Do you think this is worth continuing?

**Comment by rwjblue** [comment]
> I'm not sure what the convention should be, I guess before service injections?

Yes, agreed.

**Comment by rmachielse** [comment]
@rwjblue cool! I have added another commit, which adds `controller` injections at the first position in the `order-in-controllers` rule.

**Comment by rwjblue** [comment]
Since this introduces a breaking change, I have updated the pull request to target the `next` branch (which will eventually become 5.0.0 when we release it).

**Comment by rmachielse** [comment]
@rwjblue no problem, thanks!

**Pull request merged**
