### PR TITLE
Add additionalIgnoredProperties option to `avoid-leaking-state-in-ember-objects` rule

### LINKED ISSUE #182: avoid-leaking-state-in-ember-objects: Easily add an ignored property?
I'd like to add an additional ignored property to the avoid-leaking-state-in-ember-objects rule. It takes a list of ignored properties from the supplied options, but it's all-or-nothing: there's no easy way to add them. Can we modify this rule to merge in additional properties, or can we at least export the `DEFAULT_IGNORED_PROPERTIES` const from the module so I can append to it in .eslint.js?

### PR DESCRIPTION
**Pull request by clcuevas**
This PR fixes/resolves #182 and perhaps #192

### CODE REVIEW

**Comment by drouhard** [comment]
This looks good! Is there anything blocking it from being merged?

**Comment by clcuevas** [comment]
@rwjblue Thanks for looking into this. As far as allowing the option to remove any of the default ignored properties, what would be the case for this?

**Comment by rwjblue** [comment]
I think that #245 supersedes this, can you confirm that that addresses the main concern?

**Comment by rwjblue** [comment]
Closing for now (I think that #245 addresses the underlying issue this was trying to address)...

**Pull request closed without merging**
