### PR TITLE
add willInsertElement component lifecycle hook

### PR DESCRIPTION
**Pull request by hakubo**
This addressees: 
https://github.com/ember-cli/eslint-plugin-ember/issues/201

### CODE REVIEW

**Comment by Turbo87** [comment]
Hmm... It is indeed a breaking change, though I'd argue that it could be considered a bug fix, so I'm fine with either solution

**Comment by hakubo** [comment]
I'd err on the side of major version. We have set up our CI in a way that it triggers a fail when eslint does not pass. I don't think anyone's CI should fail unexpectedly.

**Comment by Turbo87** [comment]
Can anyone check if ESlint itself has some guidelines around this?

**Comment by kellyselden** [comment]
From experience, I've had an ESlint bugfix break my linting. I then search ESlint tracker to find the issue, to find out it is expect and my code needs to change.

Given there is precedent in ESlint, we could go either way we wanted I believe.

**Comment by hakubo** [comment]
How can I help making the decision?

**Comment by hakubo** [comment]
@Turbo87 hey, what has to happen to get this merged?

**Comment by Turbo87** [comment]
reminding me about it apparently helped 😉

**Pull request merged**
