### PR TITLE
Update `no-global-jquery` rule to account for new modules import

### PR DESCRIPTION
**Pull request by clcuevas**
This PR updates the `no-global-jquery` rule to not report the `$` module when using the new modules import syntax.

### CODE REVIEW

**Comment by clcuevas** [comment]
@rwjblue Thanks for looking into this and providing feedback. I'm definitely up for this task. Would you like for me to close this PR and open a new one once I've fixed the above issues/concerns you stated?

**Comment by rwjblue** [comment]
Totally up to you, I'm happy to iterate with you here or in separate more focused PRs. Whichever seems more comfortable for you...

**Comment by clcuevas** [comment]
Okay, I'll leave this PR open and see where it goes... 😄

**Comment by clcuevas** [comment]
@rwjblue I have something that I've labeled "WIP". I wanted to push it up here just so you can have a look and make sure I'm moving in the right direction. I'm still trying to figure out if there is a better way to perform the checks we need to make for this rule. But, this requires that I read a lot of documentation for ESLint and working with the rules, etc.

**Comment by rwjblue** [comment]
Yes, that’s looking much better! Thanks for working on it!

I think the next major thing to do is add the various test cases I listed above, and confirm the changes here address them (and adjust if not).

**Comment by clcuevas** [comment]
@rwjblue I think this is ready to go for a review!

**Comment by yads** [comment]
it would be great to get this merged in since the current default configuration contradicts itself.

**Comment by rwjblue** [comment]
Thank you again @clcuevas!

**Comment by danwenzel** [comment]
FYI:  It looks like there's one case that's still failing: https://github.com/ember-cli/eslint-plugin-ember/issues/187#issuecomment-353130981

**Pull request merged**
